import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationResultArtifactVerificationVerifierEvidenceResult as Evidence} from "./NavMissionDiagnosticsResultVerificationVerifierEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResult as Verification} from "./NavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationContract.js";
import {RUNTIME_NAV_MISSION_DIAGNOSTICS_RESULT_VERIFICATION_VERIFIER_EVIDENCE_VERIFICATION_RESULT_ORDER as ORDER} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultArtifact as Artifact,RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultEvidence as Source} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultAnchoredVerificationOptions as Options,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationResult as Result} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultTextAnchored as verifyText} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationAnchors.js";
import {add,anchors,checks,digest,equal,finalize,result,safe} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationSupport.js";
const TEXT="text/plain;charset=utf-8",JSON_MIME="application/json;charset=utf-8";
export async function verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultArtifact(source:Source,expectedVerification?:Verification,expectedEvidence?:Evidence,expectedInputEvidenceChecksumHex?:string):Promise<Result>{if(source.status!=="created")return failure("expected-evidence-mismatch",source.error??"Verification-result artifacts are unavailable.");if(!Array.isArray(source.artifacts)||source.artifacts.length!==3)return failure("artifact-count-mismatch","Verification result must contain exactly three artifacts.");const [plain,json,sum]=source.artifacts;if(!plain||!json||!sum||plain.kind!==ORDER[0]||json.kind!==ORDER[1]||sum.kind!==ORDER[2])return failure("artifact-order-mismatch","Verification-result artifacts are not in fixed order.");const options:Options={jsonFilename:json.filename,checksumArtifactText:sum.text,checksumArtifactFilename:sum.filename,textResultText:plain.text,textResultFilename:plain.filename,...(expectedVerification?{expectedVerification}:{}),...(expectedEvidence?{expectedEvidence}:{}),...(expectedInputEvidenceChecksumHex?{expectedInputEvidenceChecksumHex}:{})};const output=await verifyText(json.text,options);await envelope(source,output);finalize(output);return output}
async function envelope(source:Source,output:Result):Promise<void>{const subtle=globalThis.crypto?.subtle,start=output.issues.length;if(!subtle){output.checks.artifactEnvelope=false;return}if(source.artifactCount!==3||source.artifacts.length!==3)add(output.issues,"artifact-count-mismatch","$.artifacts","Verification-result artifact count must be three.");let total=0;for(let i=0;i<source.artifacts.length;i++){const artifact=source.artifacts[i],kind=ORDER[i],path=`$.artifacts[${i}]`;if(!artifact||artifact.kind!==kind){add(output.issues,"artifact-order-mismatch",path,"Verification-result artifact kind is out of order.");continue}const bytes=new TextEncoder().encode(artifact.text).byteLength,hash=await digest(artifact.text,subtle),mime=kind===ORDER[1]?JSON_MIME:TEXT;total+=bytes;if(!safe(artifact.filename)||artifact.mimeType!==mime||artifact.bytes!==bytes)add(output.issues,"artifact-metadata-mismatch",path,"Artifact filename, MIME type, or byte size is invalid.");if(artifact.checksumHex!==hash)add(output.issues,"sha256-mismatch",`${path}.checksumHex`,`Artifact SHA-256 does not match exact text.`)}filenames(source.artifacts,output);if(source.totalBytes!==total)add(output.issues,"artifact-metadata-mismatch","$.totalBytes","Verification-result totalBytes does not match exact artifact bytes.");if(output.document&&source.document&&!equal(output.document,source.document))add(output.issues,"expected-evidence-mismatch","$.document","Verification-result document does not match its JSON artifact.");output.checks.artifactEnvelope=output.issues.length===start}
function filenames(a:Artifact[],output:Result):void{const [plain,json,sum]=a;if(!plain||!json||!sum||!json.filename.endsWith(".json"))return;const base=json.filename.slice(0,-5);if(plain.filename!==`${base}.txt`||sum.filename!==`${json.filename}.sha256`)add(output.issues,"artifact-metadata-mismatch","$.artifacts","Verification-result artifact filenames are inconsistent.")}
function failure(code:Result["issues"][number]["code"],message:string):Result{const c=checks(true,true);c.artifactEnvelope=false;const a=anchors(false,false,false,true,true),issues:Result["issues"]=[];add(issues,code,"$",message);return result(null,null,0,null,issues,c,a)}
