import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationAnchors as Anchors,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationChecks as Checks,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationIssue as Issue,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationIssueCode as Code,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationResult as Result} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
const SAFE=/^[a-zA-Z0-9._-]+$/,SHA=/^[0-9a-f]{64}$/;
export const SOURCE_CHECK_FIELDS=["parsed","schema","canonical","input","recordedResult","result","verificationChecks","anchors","evidence","issues","jsonChecksum","textEvidence","artifactEnvelope"] as const;
export const SOURCE_ANCHOR_FIELDS=["expectedVerification","expectedSource","inputResultChecksum","jsonChecksumArtifact","textEvidenceArtifact"] as const;
export const SOURCE_EVIDENCE_FIELDS=["documentAvailable","canonicalTextAvailable","canonicalTextMatchesInput","verificationChecksumAvailable","verificationChecksumMatchesInput","issuesTruncated"] as const;
export interface Limits{maxTextBytes:number;maxStringCharacters:number;maxArrayEntries:number;maxObjectFields:number;maxDepth:number}
export function isRecord(v:unknown):v is Record<string,unknown>{return v!==null&&typeof v==="object"&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype}
export function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(isRecord(v)){const o:Record<string,unknown>={};for(const k of Object.keys(v).sort())o[k]=canonical(v[k]);return o}return v}
export function equal(a:unknown,b:unknown):boolean{return JSON.stringify(canonical(a))===JSON.stringify(canonical(b))}
export function safe(v:unknown):v is string{return typeof v==="string"&&v.length>0&&v.length<=255&&SAFE.test(v)}
export function sha(v:unknown):v is string{return typeof v==="string"&&SHA.test(v)}
export async function digest(text:string,subtle:SubtleCrypto):Promise<string>{const b=new TextEncoder().encode(text),c=new Uint8Array(b.byteLength);c.set(b);return Array.from(new Uint8Array(await subtle.digest("SHA-256",c.buffer)),x=>x.toString(16).padStart(2,"0")).join("")}
export function add(issues:Issue[],code:Code,path:string,message:string):void{issues.push({code,path,message})}
export function checks(hasChecksum:boolean,hasText:boolean):Checks{return {parsed:false,schema:false,canonical:false,input:false,recordedEvidence:false,result:false,verificationChecks:false,anchors:false,evidence:false,issues:false,jsonChecksum:!hasChecksum,textResult:!hasText,artifactEnvelope:true}}
export function anchors(expectedVerification:boolean,expectedEvidence:boolean,inputChecksum:boolean,hasChecksum:boolean,hasText:boolean):Anchors{return {expectedVerification:expectedVerification?false:null,expectedEvidence:expectedEvidence?false:null,inputEvidenceChecksum:inputChecksum?false:null,jsonChecksumArtifact:hasChecksum?false:null,textResultArtifact:hasText?false:null}}
export function result(document:Result["document"],canonicalText:string|null,bytes:number,checksumHex:string|null,issues:Issue[],verificationChecks:Checks,verificationAnchors:Anchors):Result{return {valid:false,trust:"untrusted",document,canonicalText,bytes,checksumHex,issues,checks:verificationChecks,anchors:verificationAnchors}}
export function finalize(v:Result):void{v.valid=v.issues.length===0;if(!v.valid){v.trust="untrusted";return}const trusted=[v.anchors.expectedVerification,v.anchors.expectedEvidence,v.anchors.inputEvidenceChecksum].filter((x):x is boolean=>x!==null);v.trust=trusted.length>0&&trusted.every(Boolean)?"anchored":"self-consistent"}
