import type { RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportArtifact as ReportArtifact, RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportResult as Report } from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReport.js";
import type { RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationResult as Verification } from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerification.js";
import { RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_VERIFICATION_EVIDENCE_SCHEMA as SCHEMA, RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_VERIFICATION_EVIDENCE_SCHEMA_VERSION as VERSION } from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type { RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifact as Artifact, RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactKind as Kind, RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceDocument as Document, RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceResult as Result, RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceStatus as Status } from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import {JSON_MIME,TEXT_MIME,checksum,copyAnchors,copyChecks,filenames,integer,isSafe,readTarget,recorded,string,target} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceSupport.js";
import {normalizeIssue} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceIssue.js";
import {canonicalize,digest,text as createText} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceSerialization.js";
export * from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
const MAX=4*1024*1024, MAX_ISSUES=512;
export async function createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidence(verification:Verification,report:Report):Promise<Result>{
 if(report.status!=="created")return fail("report-unavailable",verification,report,report.error??"Created provenance verification report artifacts are unavailable.");
 const source=one(report.artifacts);if(!source)return fail("report-unavailable",verification,report,"Verification report result must contain exactly one JSON artifact.");
 const subtle=globalThis.crypto?.subtle;if(!subtle)return fail("crypto-unavailable",verification,report,"Web Crypto is unavailable; deterministic verifier evidence checksums cannot be created.");
 try{const input=typeof source.text==="string"?source.text:"", exactBytes=new TextEncoder().encode(input).byteLength;if(exactBytes>MAX)return fail("input-too-large",verification,report,`Verification report JSON exceeds the ${MAX} byte evidence limit.`);
 const exact=await digest(input,subtle), filename=typeof source.filename==="string"?source.filename:"", mime=typeof source.mimeType==="string"?source.mimeType:"", declaredBytes=typeof source.bytes==="number"?source.bytes:-1, declaredChecksum=typeof source.checksumHex==="string"?source.checksumHex:"", safe=isSafe(filename), issues=Array.isArray(verification.issues)?verification.issues:[];
 const document:Document={schema:SCHEMA,schemaVersion:VERSION,target:target(readTarget(verification.document)??readTarget(report.document)),input:{verificationReportJsonFilename:safe?filename:"mission-diagnostics-policy-manifest.provenance-verification-report.json",verificationReportJsonMimeType:string(mime,255,"application/octet-stream"),declaredBytes:integer(declaredBytes),exactBytes,declaredChecksumHex:checksum(declaredChecksum),exactChecksum:{algorithm:"SHA-256",input:"verification-report-json-utf8",hex:exact},envelope:{filenameSafe:safe,mimeTypeMatches:mime===JSON_MIME,byteSizeMatches:declaredBytes===exactBytes,checksumMatches:declaredChecksum===exact}},recordedReport:recorded(verification.document??report.document),result:{valid:verification.valid,trust:verification.trust,issueCount:issues.length},checks:copyChecks(verification.checks),anchors:copyAnchors(verification.anchors),evidence:{documentAvailable:verification.document!==null,canonicalTextAvailable:typeof verification.canonicalText==="string",canonicalTextMatchesInput:typeof verification.canonicalText==="string"&&verification.canonicalText===input,verificationChecksumAvailable:typeof verification.checksumHex==="string",verificationChecksumMatchesInput:typeof verification.checksumHex==="string"&&verification.checksumHex===exact,issuesTruncated:issues.length>MAX_ISSUES},issues:issues.slice(0,MAX_ISSUES).map(normalizeIssue)};
 const names=filenames(filename),json=`${JSON.stringify(canonicalize(document),null,2)}\n`,plain=createText(document),jsonHash=await digest(json,subtle),artifacts=[await artifact("provenance-verification-report-verification-evidence-text",names.text,TEXT_MIME,plain,subtle),{kind:"provenance-verification-report-verification-evidence-json" as const,filename:names.json,mimeType:JSON_MIME,bytes:new TextEncoder().encode(json).byteLength,checksumHex:jsonHash,text:json},await artifact("provenance-verification-report-verification-evidence-json-sha256",names.checksum,TEXT_MIME,`${jsonHash}  ${names.json}\n`,subtle)];
 return {status:"created",verification,report,document,artifactCount:3,totalBytes:artifacts.reduce((n,a)=>n+a.bytes,0),artifacts,error:null};}catch(error){return fail("evidence-error",verification,report,format(error));}}
async function artifact(kind:Kind,filename:string,mimeType:Artifact["mimeType"],text:string,subtle:SubtleCrypto):Promise<Artifact>{return {kind,filename,mimeType,bytes:new TextEncoder().encode(text).byteLength,checksumHex:await digest(text,subtle),text};}
function one(a:ReportArtifact[]):ReportArtifact|null{const m=Array.isArray(a)?a.filter(x=>x?.kind==="provenance-verification-report-json"):[];return m.length===1?m[0]??null:null;}
function fail(status:Exclude<Status,"created">,verification:Verification,report:Report,error:string):Result{return {status,verification,report,document:null,artifactCount:0,totalBytes:0,artifacts:[],error};}
function format(e:unknown):string{return e instanceof Error?e.message:String(e);}
