import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationChecks as Checks,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationAnchors as Anchors} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceDocument as Document} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceContract.js";
export const JSON_MIME="application/json;charset=utf-8" as const,TEXT_MIME="text/plain;charset=utf-8" as const;const SAFE=/^[a-zA-Z0-9._-]+$/,SHA=/^[0-9a-f]{64}$/;
export const CHECK_FIELDS=["parsed","schema","canonical","input","recordedEvidence","result","verificationChecks","anchors","evidence","issues","jsonChecksum","textResult","artifactEnvelope"] as const;
export const ANCHOR_FIELDS=["expectedVerification","expectedEvidence","inputEvidenceChecksum","jsonChecksumArtifact","textResultArtifact"] as const;
export function copyChecks(v:Checks):Checks{return {...v}}export function copyAnchors(v:Anchors):Anchors{return {...v}}
export function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(v!==null&&typeof v==="object"){const s=v as Record<string,unknown>,o:Record<string,unknown>={};for(const k of Object.keys(s).sort())if(s[k]!==undefined)o[k]=canonical(s[k]);return o}return v}
export async function digest(text:string,subtle:SubtleCrypto):Promise<string>{const b=new TextEncoder().encode(text),c=new Uint8Array(b.byteLength);c.set(b);return Array.from(new Uint8Array(await subtle.digest("SHA-256",c.buffer)),x=>x.toString(16).padStart(2,"0")).join("")}
export function safe(v:string):boolean{return v.length>0&&v.length<=255&&SAFE.test(v)}export function integer(v:number):number{return Number.isSafeInteger(v)&&v>=0?v:0}export function checksum(v:string):string{return SHA.test(v)?v:"0".repeat(64)}export function string(v:string,n:number,f:string):string{return v.length>0&&v.length<=n?v:f}
export function target(v:unknown):unknown{if(v===null||typeof v!=="object"||Array.isArray(v))return null;const r=v as Record<string,unknown>,scope=typeof r.scope==="string"&&r.scope.length<=64?r.scope:null,packageIndex=r.packageIndex===null||(typeof r.packageIndex==="number"&&Number.isSafeInteger(r.packageIndex)&&r.packageIndex>=0)?r.packageIndex:null;return {packageIndex,scope}}
export function filenames(source:string){let base="mission-diagnostics-policy-manifest.verifier-evidence.verification-result";if(safe(source)&&source.endsWith(".json"))base=source.slice(0,-5);base+=".verifier-evidence";return {text:`${base}.txt`,json:`${base}.json`,checksum:`${base}.json.sha256`}}
export function createText(d:Document):string{const l=["Splat World Engine Verifier Evidence Verification Result Verifier Evidence","",`Schema: ${d.schema}`,`Schema version: ${d.schemaVersion}`,`Target: ${JSON.stringify(canonical(d.target))}`,"",`Verification-result artifact verification valid: ${d.result.valid}`,`Verification-result artifact verification trust: ${d.result.trust}`,`Verification-result artifact verification issue count: ${d.result.issueCount}`,"",`Verification result JSON: ${d.input.verificationResultJsonFilename}`,`Verification result exact bytes: ${d.input.exactBytes}`,`Verification result exact SHA-256: ${d.input.exactChecksum.hex}`,`Envelope filename safe: ${d.input.envelope.filenameSafe}`,`Envelope MIME type matches: ${d.input.envelope.mimeTypeMatches}`,`Envelope byte size matches: ${d.input.envelope.byteSizeMatches}`,`Envelope checksum matches: ${d.input.envelope.checksumMatches}`,"",`Recorded result schema: ${d.recordedResult.schema??"unavailable"}`,`Recorded result schema version: ${d.recordedResult.schemaVersion??"unavailable"}`,`Recorded verifier-evidence verification valid: ${d.recordedResult.verifierEvidenceVerificationValid??"unavailable"}`,`Recorded verifier-evidence verification trust: ${d.recordedResult.verifierEvidenceVerificationTrust??"unavailable"}`,"","Verification checks"];for(const f of CHECK_FIELDS)l.push(`  ${f}: ${d.checks[f]}`);l.push("","Trusted anchors");for(const f of ANCHOR_FIELDS){const v=d.anchors[f];l.push(`  ${f}: ${v===null?"not-provided":v}`)}l.push("","Evidence relationships",`  documentAvailable: ${d.evidence.documentAvailable}`,`  canonicalTextAvailable: ${d.evidence.canonicalTextAvailable}`,`  canonicalTextMatchesInput: ${d.evidence.canonicalTextMatchesInput}`,`  verificationChecksumAvailable: ${d.evidence.verificationChecksumAvailable}`,`  verificationChecksumMatchesInput: ${d.evidence.verificationChecksumMatchesInput}`,`  issuesTruncated: ${d.evidence.issuesTruncated}`,"","Issues");if(!d.issues.length)l.push("  none");else for(const i of d.issues)l.push(`  ${i.code} ${i.path}`,`    ${i.message}`);l.push("",`Result: ${d.result.valid?"verification-result artifact verification passed":"verification-result artifact verification failed"}`);return `${l.join("\n")}\n`}
