import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceResult as Provenance} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenance.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationResult as ProvenanceVerification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerification.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultEvidence as Source} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationResult as Verification} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceResult as Evidence} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceContract.js";
import {createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceWorkflow as createEvidenceWorkflow} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceWorkflow.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceWorkflowOptions as EvidenceWorkflowOptions} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceWorkflow.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationControlOptions as ControlOptions,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationResult as Result} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceArtifact as verifyEvidence} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationVerifier.js";
import {renderRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerification as render,verificationButton} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationRender.js";
export type RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerifiedWorkflowOptions=EvidenceWorkflowOptions&{expectedVerificationResultArtifactVerification?:Verification;expectedVerificationResultSource?:Source;expectedVerificationResultVerifierEvidenceInputResultChecksumHex?:string;onVerificationResultVerifierEvidenceVerify?:(result:Result,evidence:Evidence)=>void};
export function createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationControl(evidence:Evidence,options:ControlOptions={}):HTMLElement{const root=document.createElement("section");root.className="mission-debug-diagnostics-verification-result-artifact-verifier-evidence-verification";Object.assign(root.style,{display:"grid",gap:"5px",minWidth:"0"});root.dataset.verificationResultArtifactVerifierEvidenceVerificationStatus="idle";const button=verificationButton("Verify verification-result artifact-verifier evidence artifacts","schema · canonical JSON · result anchors · issues · text evidence · JSON SHA-256"),details=document.createElement("details");details.hidden=true;Object.assign(details.style,{minWidth:"0",padding:"6px 7px",borderRadius:"7px"});button.addEventListener("click",()=>void run(root,button,details,evidence,options));root.append(button,details);return root}
export function createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerifiedWorkflow(verification:ProvenanceVerification,provenance:Provenance,options:RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerifiedWorkflowOptions={}):HTMLElement{const root=document.createElement("section");Object.assign(root.style,{display:"grid",gap:"5px",minWidth:"0"});const workflow=createEvidenceWorkflow(verification,provenance,{...options,onVerificationResultVerifierEvidenceCreate:(e:Evidence,v:Verification,s:Source)=>{options.onVerificationResultVerifierEvidenceCreate?.(e,v,s);root.querySelector<HTMLElement>("[data-verification-result-artifact-verifier-evidence-verifier]")?.remove();if(e.status!=="created")return;const control=createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationControl(e,{expectedVerification:options.expectedVerificationResultArtifactVerification??v,expectedSource:options.expectedVerificationResultSource??s,...(options.expectedVerificationResultVerifierEvidenceInputResultChecksumHex===undefined?{}:{expectedInputResultChecksumHex:options.expectedVerificationResultVerifierEvidenceInputResultChecksumHex}),onVerify:(result,artifactSet)=>options.onVerificationResultVerifierEvidenceVerify?.(result,artifactSet),...(options.onStatus===undefined?{}:{onStatus:options.onStatus})});control.dataset.verificationResultArtifactVerifierEvidenceVerifier="true";root.append(control)}});root.append(workflow);return root}
async function run(root:HTMLElement,button:HTMLButtonElement,details:HTMLDetailsElement,evidence:Evidence,options:ControlOptions):Promise<void>{button.disabled=true;root.dataset.verificationResultArtifactVerifierEvidenceVerificationStatus="verifying";try{const output=await verifyEvidence(evidence,options.expectedVerification,options.expectedSource,options.expectedInputResultChecksumHex);dataset(root,output);render(details,output);options.onVerify?.(output,evidence);options.onStatus?.(output.valid?`Verification-result artifact-verifier evidence verified with ${output.trust} trust.`:`Verification-result artifact-verifier evidence verification failed with ${output.issues.length} issues.`)}catch(error){root.dataset.verificationResultArtifactVerifierEvidenceVerificationStatus="error";details.hidden=false;details.open=true;const s=document.createElement("summary"),m=document.createElement("small");s.textContent="Verification-result artifact-verifier evidence verification error";m.textContent=error instanceof Error?error.message:String(error);details.replaceChildren(s,m);options.onStatus?.(`Verification-result artifact-verifier evidence verification error: ${m.textContent}`)}finally{button.disabled=false}}
function dataset(root:HTMLElement,v:Result):void{root.dataset.verificationResultArtifactVerifierEvidenceVerificationStatus=v.valid?"verified":"failed";root.dataset.verificationResultArtifactVerifierEvidenceVerificationValid=String(v.valid);root.dataset.verificationResultArtifactVerifierEvidenceVerificationTrust=v.trust;root.dataset.verificationResultArtifactVerifierEvidenceVerificationIssueCount=String(v.issues.length);if(v.document){root.dataset.verificationResultArtifactVerifierEvidenceVerificationSchemaVersion=String(v.document.schemaVersion);root.dataset.verificationResultArtifactVerifierEvidenceVerificationRecordedValid=String(v.document.result.valid);root.dataset.verificationResultArtifactVerifierEvidenceVerificationRecordedTrust=v.document.result.trust}if(v.checksumHex)root.dataset.verificationResultArtifactVerifierEvidenceVerificationChecksum=v.checksumHex}
