import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceDocument as Document} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceContract.js";
import {createText as evidenceText} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceSupport.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationAnchors as Anchors,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationChecks as Checks,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationIssue as Issue,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationOptions as Options,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationResult as Result} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceDocument as verifyDocument} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationDocument.js";
import {add,anchors,canonical,checks,digest,finalize,isRecord,result,safe,sha,type Limits} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationSupport.js";
export * from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationContract.js";
const DEFAULTS={maxTextBytes:4*1024*1024,maxStringCharacters:1024*1024,maxArrayEntries:512,maxObjectFields:64,maxDepth:32};
export async function verifyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceText(text:string,options:Options={}):Promise<Result>{const c=checks(options.checksumArtifactText!==undefined,options.textEvidenceText!==undefined),a=anchors(false,false,options.expectedInputResultChecksumHex!==undefined,options.checksumArtifactText!==undefined,options.textEvidenceText!==undefined),issues:Issue[]=[];if(typeof text!=="string")return early("text-invalid","$","Result-verifier evidence input must be a string.",c,a);const bytes=new TextEncoder().encode(text).byteLength,limits=normalize(options);if(bytes>limits.maxTextBytes)return early("text-size-invalid","$",`Result-verifier evidence exceeds ${limits.maxTextBytes} bytes.`,c,a,bytes);let parsed:unknown;try{parsed=JSON.parse(text);c.parsed=true}catch{return early("json-parse-failed","$","Result-verifier evidence text is not valid JSON.",c,a,bytes)}if(!isRecord(parsed))return early("document-type-invalid","$","Result-verifier evidence root must be a plain object.",c,a,bytes);const canonicalText=`${JSON.stringify(canonical(parsed),null,2)}\n`;c.canonical=canonicalText===text;if(!c.canonical)add(issues,"canonical-json-mismatch","$","Result-verifier evidence JSON is not canonical.");const document=verifyDocument(parsed,limits,issues,c);let checksumHex:string|null=null;const subtle=globalThis.crypto?.subtle;if(!subtle)add(issues,"crypto-unavailable","$","Web Crypto SHA-256 is unavailable.");else{checksumHex=await digest(text,subtle);c.jsonChecksum=checksumArtifact(checksumHex,options,issues,a);c.textEvidence=textArtifact(document,options,issues,a)}inputAnchor(document,options.expectedInputResultChecksumHex,issues,a);const output=result(document,canonicalText,bytes,checksumHex,issues,c,a);finalize(output);return output}
function checksumArtifact(hash:string,o:Options,issues:Issue[],a:Anchors):boolean{if(o.checksumArtifactText===undefined)return true;const name=o.jsonFilename;let valid=typeof name==="string"&&safe(name)&&o.checksumArtifactText===`${hash}  ${name}\n`;if(o.checksumArtifactFilename!==undefined)valid=valid&&o.checksumArtifactFilename===`${name}.sha256`;if(!valid)add(issues,"checksum-artifact-invalid","$.artifacts","Result-verifier evidence JSON SHA-256 artifact is invalid.");a.jsonChecksumArtifact=valid;return valid}
function textArtifact(document:Document|null,o:Options,issues:Issue[],a:Anchors):boolean{if(o.textEvidenceText===undefined)return true;let valid=document!==null&&o.textEvidenceText===evidenceText(document);if(o.textEvidenceFilename!==undefined&&o.jsonFilename!==undefined)valid=valid&&o.jsonFilename.endsWith(".json")&&o.textEvidenceFilename===`${o.jsonFilename.slice(0,-5)}.txt`;if(!valid)add(issues,"text-evidence-mismatch","$.artifacts","Result-verifier evidence text artifact is invalid.");a.textEvidenceArtifact=valid;return valid}
function inputAnchor(document:Document|null,expected:string|undefined,issues:Issue[],a:Anchors):void{if(expected===undefined)return;const valid=sha(expected)&&document?.input.exactChecksum.hex===expected;if(!valid)add(issues,"expected-input-checksum-mismatch","$.input.exactChecksum.hex","Input verification-result checksum does not match the trusted anchor.");a.inputResultChecksum=valid}
function early(code:Issue["code"],path:string,message:string,c:Checks,a:Anchors,bytes=0):Result{const issues:Issue[]=[];add(issues,code,path,message);return result(null,null,bytes,null,issues,c,a)}
function normalize(o:Options):Limits{return {maxTextBytes:positive(o.maxTextBytes,DEFAULTS.maxTextBytes,"maxTextBytes"),maxStringCharacters:positive(o.maxStringCharacters,DEFAULTS.maxStringCharacters,"maxStringCharacters"),maxArrayEntries:positive(o.maxArrayEntries,DEFAULTS.maxArrayEntries,"maxArrayEntries"),maxObjectFields:positive(o.maxObjectFields,DEFAULTS.maxObjectFields,"maxObjectFields"),maxDepth:positive(o.maxDepth,DEFAULTS.maxDepth,"maxDepth")}}
function positive(v:number|undefined,f:number,label:string):number{if(v===undefined)return f;if(!Number.isSafeInteger(v)||v<=0)throw new Error(`${label} must be a positive safe integer.`);return v}
