import {createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidence as createEvidence} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifacts.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportResult as Report} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReport.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationResult as Verification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerification.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceActionsOptions as Options,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceResult as Result} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import {actionButton,createEvidenceInspection,downloadEvidenceArtifact,downloadEvidenceArtifacts,copyEvidenceArtifact,formatBytes,formatError} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactActions.js";
const PREVIEW=4096;
export const downloadRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifact=downloadEvidenceArtifact;
export const downloadRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifacts=downloadEvidenceArtifacts;
export const copyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifact=copyEvidenceArtifact;
export function createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceActions(v:Verification,r:Report,o:Options={}):HTMLElement{const root=section(),s=document.createElement("small");s.textContent="Preparing deterministic verification-report verifier evidence artifacts…";s.style.opacity="0.66";root.append(s);void createEvidence(v,r).then(x=>render(root,x,o));return root;}
export function createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceResultActions(r:Result,o:Options={}):HTMLElement{const root=section();render(root,r,o);return root;}
function section():HTMLElement{const r=document.createElement("section");r.className="mission-debug-diagnostics-manifest-validation-imported-archive-provenance-verification-report-verification-evidence";r.dataset.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceStatus="preparing";Object.assign(r.style,{display:"grid",gap:"5px",minWidth:"0",paddingTop:"2px"});return r;}
function render(root:HTMLElement,r:Result,o:Options):void{root.dataset.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceStatus=r.status;o.onCreate?.(r);if(r.status!=="created"||!r.document){clear(root);const e=document.createElement("small");e.textContent=`Verification-report verifier evidence unavailable: ${r.error??"Unknown failure."}`;e.style.color="#ffb4b4";e.style.overflowWrap="anywhere";root.replaceChildren(e);return;}const j=r.artifacts.find(a=>a.kind==="provenance-verification-report-verification-evidence-json"),d=r.document,ds=root.dataset;ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceValid=String(d.result.valid);ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceTrust=d.result.trust;ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceIssueCount=String(d.result.issueCount);ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactCount=String(r.artifactCount);ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceTotalBytes=String(r.totalBytes);ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceInputChecksum=d.input.exactChecksum.hex;if(j)ds.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceJsonChecksum=j.checksumHex;const h=document.createElement("small");h.textContent=`Verification-report verifier evidence · ${d.result.trust} · ${d.result.issueCount} issues · ${r.artifactCount} artifacts`;h.style.fontWeight="750";h.style.overflowWrap="anywhere";const all=actionButton("Download all verifier evidence artifacts",`${r.artifactCount} artifacts · canonical fixed order · ${formatBytes(r.totalBytes)}`);all.dataset.bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceAction="download-all";all.addEventListener("click",()=>{try{const n=downloadEvidenceArtifacts(r);o.onDownloadAll?.(r);o.onStatus?.(`Downloaded ${n} verification-report verifier evidence artifacts.`);}catch(e){o.onStatus?.(`Verifier evidence download failed: ${formatError(e)}`);}});const list=document.createElement("div");Object.assign(list.style,{display:"grid",gap:"5px"});const max=preview(o.maxPreviewCharacters);for(const a of r.artifacts)list.append(createEvidenceInspection(a,r,max,o));root.replaceChildren(h,all,list);}
function clear(r:HTMLElement):void{for(const k of ["bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceValid","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceTrust","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceIssueCount","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactCount","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceTotalBytes","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceInputChecksum","bundleImportedArchiveProvenanceVerificationReportVerificationEvidenceJsonChecksum"])delete r.dataset[k];}
function preview(v:number|undefined):number{if(v===undefined)return PREVIEW;if(!Number.isSafeInteger(v)||v<=0)throw new Error("maxPreviewCharacters must be a positive safe integer.");return v;}
