import {RUNTIME_NAV_MISSION_DIAGNOSTICS_ARTIFACT_VERIFIER_EVIDENCE_VERIFICATION_RESULT_VERIFIER_EVIDENCE_VERIFICATION_RESULT_ORDER as ORDER} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultArtifact as Artifact,RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultEvidence as Source} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResult as Verification} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationContract.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceResult as ExpectedSource} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultAnchoredVerificationOptions as Options,RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationResult as Result} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultTextAnchored as verifyText} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationVerification.js";
import {JSON_MIME,TEXT_MIME,add,anchors,checks,digest,equal,finalize,result,safe} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationSupport.js";

export async function verifyRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultArtifact(source:Source,expectedVerification?:Verification,expectedSource?:ExpectedSource,expectedInputEvidenceChecksumHex?:string):Promise<Result>{const hasExpectedVerification=expectedVerification!==undefined,hasExpectedSource=expectedSource!==undefined,hasExpectedChecksum=expectedInputEvidenceChecksumHex!==undefined;if(source.status!=="created")return failure("expected-source-mismatch",source.error??"Verification-result artifacts are unavailable.",hasExpectedVerification,hasExpectedSource,hasExpectedChecksum);if(!Array.isArray(source.artifacts)||source.artifacts.length!==3)return failure("artifact-count-mismatch","Verification-result must contain exactly three artifacts.",hasExpectedVerification,hasExpectedSource,hasExpectedChecksum);const [plain,json,sum]=source.artifacts;if(!plain||!json||!sum||plain.kind!==ORDER[0]||json.kind!==ORDER[1]||sum.kind!==ORDER[2])return failure("artifact-order-mismatch","Verification-result artifacts are not in fixed order.",hasExpectedVerification,hasExpectedSource,hasExpectedChecksum);const options:Options={jsonFilename:json.filename,checksumArtifactText:sum.text,checksumArtifactFilename:sum.filename,textResultText:plain.text,textResultFilename:plain.filename,...(expectedVerification?{expectedVerification}:{}),...(expectedSource?{expectedSource}:{}),...(expectedInputEvidenceChecksumHex?{expectedInputEvidenceChecksumHex}:{})};const output=await verifyText(json.text,options);await verifyEnvelope(source,output);finalize(output);return output}
async function verifyEnvelope(source:Source,output:Result):Promise<void>{const subtle=globalThis.crypto?.subtle,start=output.issues.length;if(!subtle){output.checks.artifactEnvelope=false;return}if(source.artifactCount!==3||source.artifacts.length!==3)add(output.issues,"artifact-count-mismatch","$.artifacts","Verification-result artifact count must be three.");let total=0;for(let index=0;index<source.artifacts.length;index++){const artifact=source.artifacts[index],kind=ORDER[index],path=`$.artifacts[${index}]`;if(!artifact||artifact.kind!==kind){add(output.issues,"artifact-order-mismatch",path,"Verification-result artifact kind is out of order.");continue}const bytes=new TextEncoder().encode(artifact.text).byteLength,hash=await digest(artifact.text,subtle),mime=kind===ORDER[1]?JSON_MIME:TEXT_MIME;total+=bytes;if(!safe(artifact.filename)||artifact.mimeType!==mime||artifact.bytes!==bytes)add(output.issues,"artifact-metadata-mismatch",path,"Artifact filename, MIME type, or byte size is invalid.");if(artifact.checksumHex!==hash)add(output.issues,"sha256-mismatch",`${path}.checksumHex`,`Artifact SHA-256 does not match exact UTF-8 text.`)}verifyFilenames(source.artifacts,output);if(source.totalBytes!==total)add(output.issues,"artifact-metadata-mismatch","$.totalBytes","Verification-result totalBytes does not match exact artifact bytes.");if(output.document&&source.document&&!equal(output.document,source.document))add(output.issues,"expected-source-mismatch","$.document","Verification-result document does not match its JSON artifact.");output.checks.artifactEnvelope=output.issues.length===start}
function verifyFilenames(artifacts:Artifact[],output:Result):void{const [plain,json,sum]=artifacts;if(!plain||!json||!sum||!json.filename.endsWith(".json")){add(output.issues,"artifact-metadata-mismatch","$.artifacts","Verification-result artifact filenames are invalid.");return}const base=json.filename.slice(0,-5);if(plain.filename!==`${base}.txt`||sum.filename!==`${json.filename}.sha256`)add(output.issues,"artifact-metadata-mismatch","$.artifacts","Verification-result artifact filenames are inconsistent.")}
function failure(code:Result["issues"][number]["code"],message:string,expectedVerification:boolean,expectedSource:boolean,inputChecksum:boolean):Result{const verificationChecks=checks(true,true);verificationChecks.artifactEnvelope=false;const verificationAnchors=anchors(expectedVerification,expectedSource,inputChecksum,true,true),issues:Result["issues"]=[];add(issues,code,"$",message);return result(null,null,0,null,issues,verificationChecks,verificationAnchors)}
