import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceResult as Evidence} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResult as Verification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationContract.js";
import {createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResult as createResult} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifacts.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultActionsOptions as Options,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultEvidence as Result} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultContract.js";
import {button,bytes,copyResultArtifact,downloadResultArtifact,downloadResultArtifacts,format,inspection} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactActions.js";
const PREVIEW=4096;export const downloadRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifact=downloadResultArtifact;export const downloadRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifacts=downloadResultArtifacts;export const copyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifact=copyResultArtifact;
export function createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultActions(v:Verification,e:Evidence,o:Options={}):HTMLElement{const r=section(),s=document.createElement("small");s.textContent="Preparing deterministic evidence-verification result artifacts…";r.append(s);void createResult(v,e).then(x=>render(r,x,o));return r}
export function createRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultResultActions(v:Result,o:Options={}):HTMLElement{const r=section();render(r,v,o);return r}
function section():HTMLElement{const r=document.createElement("section");r.dataset.evidenceVerificationResultStatus="preparing";Object.assign(r.style,{display:"grid",gap:"5px",minWidth:"0"});return r}
function render(root:HTMLElement,r:Result,o:Options):void{root.dataset.evidenceVerificationResultStatus=r.status;o.onCreate?.(r);if(r.status!=="created"||!r.document){const x=document.createElement("small");x.textContent=`Evidence verification result unavailable: ${r.error??"Unknown failure."}`;x.style.color="#ffb4b4";root.replaceChildren(x);return}const j=r.artifacts.find(a=>a.kind==="report-verifier-evidence-verification-result-json"),d=r.document;root.dataset.evidenceVerificationResultValid=String(d.result.valid);root.dataset.evidenceVerificationResultTrust=d.result.trust;root.dataset.evidenceVerificationResultIssueCount=String(d.result.issueCount);root.dataset.evidenceVerificationResultArtifactCount=String(r.artifactCount);root.dataset.evidenceVerificationResultInputChecksum=d.input.exactChecksum.hex;if(j)root.dataset.evidenceVerificationResultJsonChecksum=j.checksumHex;const h=document.createElement("small");h.textContent=`Evidence verification result · ${d.result.trust} · ${d.result.issueCount} issues · ${r.artifactCount} artifacts`;h.style.fontWeight="750";const all=button(`Download all verification result artifacts · ${bytes(r.totalBytes)}`);all.addEventListener("click",()=>{try{const n=downloadResultArtifacts(r);o.onDownloadAll?.(r);o.onStatus?.(`Downloaded ${n} evidence verification result artifacts.`)}catch(e){o.onStatus?.(`Verification result download failed: ${format(e)}`)}});const list=document.createElement("div");Object.assign(list.style,{display:"grid",gap:"5px"});const max=preview(o.maxPreviewCharacters);for(const a of r.artifacts)list.append(inspection(a,r,max,o));root.replaceChildren(h,all,list)}
function preview(v:number|undefined):number{if(v===undefined)return PREVIEW;if(!Number.isSafeInteger(v)||v<=0)throw new Error("maxPreviewCharacters must be a positive safe integer.");return v}
