import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceResult as Provenance} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenance.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationResult as ProvenanceVerification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerification.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationEvidenceArtifactVerificationResultArtifactVerificationVerifierEvidenceResult as Evidence} from "./NavMissionDiagnosticsResultVerificationVerifierEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResult as Verification} from "./NavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationContract.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultEvidence as Source} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import {createRuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultWorkflow as createResultWorkflow} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultWorkflow.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultWorkflowOptions as ResultWorkflowOptions} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultWorkflow.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationControlOptions as ControlOptions,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationResult as Result} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultArtifact as verifyResult} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationVerifier.js";
import {renderRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerification as render,verificationButton} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationRender.js";
export type RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifiedWorkflowOptions=ResultWorkflowOptions&{expectedVerifierEvidenceVerification?:Verification;expectedVerifierEvidence?:Evidence;expectedVerifierEvidenceVerificationInputEvidenceChecksumHex?:string;onVerifierEvidenceVerificationResultVerify?:(result:Result,source:Source)=>void};
export function createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationControl(source:Source,options:ControlOptions={}):HTMLElement{const root=document.createElement("section");root.className="mission-debug-diagnostics-verifier-evidence-verification-result-verification";Object.assign(root.style,{display:"grid",gap:"5px",minWidth:"0"});root.dataset.verifierEvidenceVerificationResultVerificationStatus="idle";const button=verificationButton("Verify verifier-evidence verification-result artifacts","schema · canonical JSON · evidence anchors · issues · text result · JSON SHA-256"),details=document.createElement("details");details.hidden=true;Object.assign(details.style,{minWidth:"0",padding:"6px 7px",borderRadius:"7px"});button.addEventListener("click",()=>void run(root,button,details,source,options));root.append(button,details);return root}
export function createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifiedWorkflow(verification:ProvenanceVerification,provenance:Provenance,options:RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifiedWorkflowOptions={}):HTMLElement{const root=document.createElement("section");Object.assign(root.style,{display:"grid",gap:"5px",minWidth:"0"});const workflow=createResultWorkflow(verification,provenance,{...options,onVerifierEvidenceVerificationResultCreate:(source:Source,v:Verification,e:Evidence)=>{options.onVerifierEvidenceVerificationResultCreate?.(source,v,e);root.querySelector<HTMLElement>("[data-verifier-evidence-verification-result-verifier]")?.remove();if(source.status!=="created")return;const control=createRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationControl(source,{expectedVerification:options.expectedVerifierEvidenceVerification??v,expectedEvidence:options.expectedVerifierEvidence??e,...(options.expectedVerifierEvidenceVerificationInputEvidenceChecksumHex===undefined?{}:{expectedInputEvidenceChecksumHex:options.expectedVerifierEvidenceVerificationInputEvidenceChecksumHex}),onVerify:(result,artifactSet)=>options.onVerifierEvidenceVerificationResultVerify?.(result,artifactSet),...(options.onStatus===undefined?{}:{onStatus:options.onStatus})});control.dataset.verifierEvidenceVerificationResultVerifier="true";root.append(control)}});root.append(workflow);return root}
async function run(root:HTMLElement,button:HTMLButtonElement,details:HTMLDetailsElement,source:Source,options:ControlOptions):Promise<void>{button.disabled=true;root.dataset.verifierEvidenceVerificationResultVerificationStatus="verifying";try{const output=await verifyResult(source,options.expectedVerification,options.expectedEvidence,options.expectedInputEvidenceChecksumHex);dataset(root,output);render(details,output);options.onVerify?.(output,source);options.onStatus?.(output.valid?`Verifier-evidence verification-result artifacts verified with ${output.trust} trust.`:`Verifier-evidence verification-result verification failed with ${output.issues.length} issues.`)}catch(error){root.dataset.verifierEvidenceVerificationResultVerificationStatus="error";details.hidden=false;details.open=true;const s=document.createElement("summary"),m=document.createElement("small");s.textContent="Verifier-evidence verification-result verification error";m.textContent=error instanceof Error?error.message:String(error);details.replaceChildren(s,m);options.onStatus?.(`Verifier-evidence verification-result verification error: ${m.textContent}`)}finally{button.disabled=false}}
function dataset(root:HTMLElement,v:Result):void{root.dataset.verifierEvidenceVerificationResultVerificationStatus=v.valid?"verified":"failed";root.dataset.verifierEvidenceVerificationResultVerificationValid=String(v.valid);root.dataset.verifierEvidenceVerificationResultVerificationTrust=v.trust;root.dataset.verifierEvidenceVerificationResultVerificationIssueCount=String(v.issues.length);if(v.document){root.dataset.verifierEvidenceVerificationResultVerificationSchemaVersion=String(v.document.schemaVersion);root.dataset.verifierEvidenceVerificationResultVerificationRecordedValid=String(v.document.result.valid);root.dataset.verifierEvidenceVerificationResultVerificationRecordedTrust=v.document.result.trust}if(v.checksumHex)root.dataset.verifierEvidenceVerificationResultVerificationChecksum=v.checksumHex}
