import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceResult as Provenance} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenance.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationResult as ProvenanceVerification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerification.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceResult as Source} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResult as Verification} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationContract.js";
import {createRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceWorkflow as createVerifiedWorkflow} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceWorkflow.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceWorkflowOptions as VerifiedOptions} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceWorkflow.js";
import {createRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResult as createResult} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultArtifacts.js";
import {createRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultResultActions as createActions} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultActions.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultActionsOptions as ResultOptions,RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultEvidence as Result} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultContract.js";
import {createRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationControl as createVerificationControl} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationControl.js";
import type {RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationResult as ResultVerification} from "./NavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultVerificationContract.js";

export type RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultWorkflowOptions=VerifiedOptions&Omit<ResultOptions,"maxPreviewCharacters"|"onCreate"|"onArtifactDownload"|"onDownloadAll"|"onArtifactCopy">&{
  maxVerificationResultVerifierEvidenceVerificationResultPreviewCharacters?:number;
  onVerificationResultVerifierEvidenceVerificationResultCreate?:(result:Result,verification:Verification,source:Source)=>void;
  onVerificationResultVerifierEvidenceVerificationResultArtifactDownload?:ResultOptions["onArtifactDownload"];
  onVerificationResultVerifierEvidenceVerificationResultDownloadAll?:ResultOptions["onDownloadAll"];
  onVerificationResultVerifierEvidenceVerificationResultArtifactCopy?:ResultOptions["onArtifactCopy"];
  expectedVerificationResultVerifierEvidenceVerificationResultVerification?:Verification;
  expectedVerificationResultVerifierEvidenceVerificationResultSource?:Source;
  expectedVerificationResultVerifierEvidenceVerificationResultInputChecksumHex?:string;
  onVerificationResultVerifierEvidenceVerificationResultVerify?:(result:ResultVerification,source:Result)=>void;
};

export function createRuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultWorkflow(verification:ProvenanceVerification,provenance:Provenance,options:RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultWorkflowOptions={}):HTMLElement{
  const root=document.createElement("section");Object.assign(root.style,{display:"grid",gap:"5px",minWidth:"0"});let sequence=0;
  const {onArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerify:stageVerify,...verifiedOptions}=options;
  const workflow=createVerifiedWorkflow(verification,provenance,{...verifiedOptions,onArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerify:(value:Verification,source:Source)=>{stageVerify?.(value,source);const current=++sequence;root.dataset.verificationResultVerifierEvidenceVerificationResultSequence=String(current);void render(root,current,value,source,options)}});
  root.append(workflow);return root;
}

async function render(root:HTMLElement,sequence:number,verification:Verification,source:Source,options:RuntimeNavMissionDiagnosticsArtifactVerifierEvidenceVerificationResultVerifierEvidenceVerificationResultWorkflowOptions):Promise<void>{
  const result=await createResult(verification,source);
  if(sequence!==Number(root.dataset.verificationResultVerifierEvidenceVerificationResultSequence))return;
  root.querySelector<HTMLElement>("[data-verification-result-verifier-evidence-verification-result-actions]")?.remove();
  root.querySelector<HTMLElement>("[data-verification-result-verifier-evidence-verification-result-verifier]")?.remove();
  options.onVerificationResultVerifierEvidenceVerificationResultCreate?.(result,verification,source);
  const actions=createActions(result,{...(options.maxVerificationResultVerifierEvidenceVerificationResultPreviewCharacters===undefined?{}:{maxPreviewCharacters:options.maxVerificationResultVerifierEvidenceVerificationResultPreviewCharacters}),...(options.onVerificationResultVerifierEvidenceVerificationResultArtifactDownload===undefined?{}:{onArtifactDownload:options.onVerificationResultVerifierEvidenceVerificationResultArtifactDownload}),...(options.onVerificationResultVerifierEvidenceVerificationResultDownloadAll===undefined?{}:{onDownloadAll:options.onVerificationResultVerifierEvidenceVerificationResultDownloadAll}),...(options.onVerificationResultVerifierEvidenceVerificationResultArtifactCopy===undefined?{}:{onArtifactCopy:options.onVerificationResultVerifierEvidenceVerificationResultArtifactCopy}),...(options.onStatus===undefined?{}:{onStatus:options.onStatus})});
  actions.dataset.verificationResultVerifierEvidenceVerificationResultActions="true";root.append(actions);
  if(result.status!=="created")return;
  const control=createVerificationControl(result,{expectedVerification:options.expectedVerificationResultVerifierEvidenceVerificationResultVerification??verification,expectedSource:options.expectedVerificationResultVerifierEvidenceVerificationResultSource??source,...(options.expectedVerificationResultVerifierEvidenceVerificationResultInputChecksumHex===undefined?{}:{expectedInputEvidenceChecksumHex:options.expectedVerificationResultVerifierEvidenceVerificationResultInputChecksumHex}),onVerify:(value,artifactSet)=>options.onVerificationResultVerifierEvidenceVerificationResultVerify?.(value,artifactSet),...(options.onStatus===undefined?{}:{onStatus:options.onStatus})});
  control.dataset.verificationResultVerifierEvidenceVerificationResultVerifier="true";root.append(control);
}
