import {RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_SCHEMA as REPORT_SCHEMA,RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_SCHEMA_VERSION as REPORT_VERSION} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReport.js";
import {RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_VERIFICATION_EVIDENCE_SCHEMA as SCHEMA,RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_VERIFICATION_EVIDENCE_SCHEMA_VERSION as VERSION} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceDocument as Document} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationChecks as Checks,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationIssue as Issue} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationContract.js";
import type {Limits} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationSupport.js";
import {ANCHOR_FIELDS,CHECK_FIELDS,EVIDENCE_FIELDS,add,safe} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationSupport.js";
import {boolean,boolRecord,bounds,checksum,exact,filename,integer,nullableString,record,string,trust,type RecordValue} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationFields.js";
import {relationships} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationRelationships.js";
const TOP=["schema","schemaVersion","target","input","recordedReport","result","checks","anchors","evidence","issues"] as const,TARGET=["packageIndex","scope"] as const,INPUT=["verificationReportJsonFilename","verificationReportJsonMimeType","declaredBytes","exactBytes","declaredChecksumHex","exactChecksum","envelope"] as const,CHECKSUM=["algorithm","input","hex"] as const,ENVELOPE=["filenameSafe","mimeTypeMatches","byteSizeMatches","checksumMatches"] as const,RECORDED=["schema","schemaVersion","provenanceResultValid","provenanceResultTrust"] as const,RESULT=["valid","trust","issueCount"] as const,ISSUE=["code","path","message"] as const;
export function verifyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceDocument(value:RecordValue,limits:Limits,issues:Issue[],checks:Checks):Document|null{
 bounds(value,"$",0,limits,issues);exact(value,TOP,"$",issues);checks.schema=schema(value,issues);
 if(value.target!==null){const t=record(value.target,"$.target",issues);if(t){exact(t,TARGET,"$.target",issues);nullableString(t.scope,"$.target.scope",64,issues);if(t.packageIndex!==null)integer(t.packageIndex,"$.target.packageIndex",issues)}}
 const input=record(value.input,"$.input",issues),recorded=record(value.recordedReport,"$.recordedReport",issues),result=record(value.result,"$.result",issues),verificationChecks=record(value.checks,"$.checks",issues),anchors=record(value.anchors,"$.anchors",issues),evidence=record(value.evidence,"$.evidence",issues),entries=Array.isArray(value.issues)?value.issues:null;if(!entries)add(issues,"field-type-invalid","$.issues","issues must be an array.");
 checks.input=verifyInput(input,issues);checks.recordedReport=verifyRecorded(recorded,issues);checks.result=verifyResult(result,issues);checks.verificationChecks=boolRecord(verificationChecks,CHECK_FIELDS,"$.checks",issues);checks.anchors=boolRecord(anchors,ANCHOR_FIELDS,"$.anchors",issues,true);checks.evidence=verifyEvidence(evidence,issues);checks.issues=verifyIssues(entries,issues);relationships(result,verificationChecks,anchors,evidence,entries,checks,issues);
 return checks.schema&&checks.input&&checks.recordedReport&&checks.result&&checks.verificationChecks&&checks.anchors&&checks.evidence&&checks.issues?value as unknown as Document:null;
}
function schema(v:RecordValue,issues:Issue[]):boolean{const n=issues.length;if(v.schema!==SCHEMA)add(issues,"schema-mismatch","$.schema","Verifier evidence schema mismatch.");if(v.schemaVersion!==VERSION)add(issues,"schema-version-mismatch","$.schemaVersion","Verifier evidence schema version mismatch.");return issues.length===n}
function verifyInput(v:RecordValue|null,issues:Issue[]):boolean{if(!v)return false;const n=issues.length;exact(v,INPUT,"$.input",issues);const name=filename(v.verificationReportJsonFilename,"$.input.verificationReportJsonFilename",issues),mime=string(v.verificationReportJsonMimeType,"$.input.verificationReportJsonMimeType",255,issues),declared=integer(v.declaredBytes,"$.input.declaredBytes",issues),exactBytes=integer(v.exactBytes,"$.input.exactBytes",issues),declaredHash=checksum(v.declaredChecksumHex,"$.input.declaredChecksumHex",issues),sum=record(v.exactChecksum,"$.input.exactChecksum",issues),env=record(v.envelope,"$.input.envelope",issues);if(sum){exact(sum,CHECKSUM,"$.input.exactChecksum",issues);if(sum.algorithm!=="SHA-256")add(issues,"field-value-invalid","$.input.exactChecksum.algorithm","Algorithm must be SHA-256.");if(sum.input!=="verification-report-json-utf8")add(issues,"field-value-invalid","$.input.exactChecksum.input","Checksum input mismatch.");checksum(sum.hex,"$.input.exactChecksum.hex",issues)}boolRecord(env,ENVELOPE,"$.input.envelope",issues);if(env){if(env.filenameSafe!==(name!==null&&safe(name))||env.mimeTypeMatches!==(mime==="application/json;charset=utf-8")||env.byteSizeMatches!==(declared!==null&&declared===exactBytes)||env.checksumMatches!==(declaredHash!==null&&sum?.hex===declaredHash))add(issues,"input-envelope-mismatch","$.input.envelope","Input envelope booleans are inconsistent.")}return issues.length===n}
function verifyRecorded(v:RecordValue|null,issues:Issue[]):boolean{if(!v)return false;const n=issues.length;exact(v,RECORDED,"$.recordedReport",issues);if(v.schema!==null&&v.schema!==REPORT_SCHEMA)add(issues,"recorded-report-mismatch","$.recordedReport.schema","Recorded report schema mismatch.");if(v.schemaVersion!==null&&v.schemaVersion!==REPORT_VERSION)add(issues,"recorded-report-mismatch","$.recordedReport.schemaVersion","Recorded report schema version mismatch.");if(v.provenanceResultValid!==null)boolean(v.provenanceResultValid,"$.recordedReport.provenanceResultValid",issues);if(v.provenanceResultTrust!==null)trust(v.provenanceResultTrust,"$.recordedReport.provenanceResultTrust",issues);return issues.length===n}
function verifyResult(v:RecordValue|null,issues:Issue[]):boolean{if(!v)return false;const n=issues.length;exact(v,RESULT,"$.result",issues);const valid=boolean(v.valid,"$.result.valid",issues),t=trust(v.trust,"$.result.trust",issues),count=integer(v.issueCount,"$.result.issueCount",issues);if(valid===true&&(t==="untrusted"||count!==0))add(issues,"result-mismatch","$.result","Valid result cannot be untrusted or retain issues.");if(valid===false&&(t!=="untrusted"||count===0))add(issues,"result-mismatch","$.result","Invalid result must be untrusted and retain issues.");return issues.length===n}
function verifyEvidence(v:RecordValue|null,issues:Issue[]):boolean{if(!v)return false;const n=issues.length;boolRecord(v,EVIDENCE_FIELDS,"$.evidence",issues);if(v.canonicalTextMatchesInput===true&&v.canonicalTextAvailable!==true)add(issues,"evidence-mismatch","$.evidence.canonicalTextMatchesInput","Canonical match requires canonical text.");if(v.verificationChecksumMatchesInput===true&&v.verificationChecksumAvailable!==true)add(issues,"evidence-mismatch","$.evidence.verificationChecksumMatchesInput","Checksum match requires checksum evidence.");return issues.length===n}
function verifyIssues(v:unknown[]|null,issues:Issue[]):boolean{if(!v)return false;const n=issues.length;for(let i=0;i<v.length;i++){const x=record(v[i],`$.issues[${i}]`,issues);if(!x)continue;exact(x,ISSUE,`$.issues[${i}]`,issues);string(x.code,`$.issues[${i}].code`,128,issues);const p=string(x.path,`$.issues[${i}].path`,2048,issues);if(p&&!p.startsWith("$"))add(issues,"issue-evidence-mismatch",`$.issues[${i}].path`,"Issue path must start with $.");string(x.message,`$.issues[${i}].message`,512,issues)}return issues.length===n}
