import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportResult as Report} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReport.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationResult as Verification} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerification.js";
import {RUNTIME_NAV_MISSION_DIAGNOSTICS_MANIFEST_VALIDATION_ARTIFACT_BUNDLE_IMPORTED_ARCHIVE_PROVENANCE_VERIFICATION_REPORT_VERIFICATION_EVIDENCE_ORDER as ORDER} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifact as Artifact,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceResult as Evidence} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceAnchoredVerificationOptions as Options,RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResult as Result} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceTextAnchored as verifyText} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceAnchorVerification.js";
import {add,anchors,checks,digest,equal,finalize,result,safe} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationSupport.js";
const TEXT="text/plain;charset=utf-8",JSON_MIME="application/json;charset=utf-8";
export async function verifyRuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifact(evidence:Evidence,expectedVerification?:Verification,expectedReport?:Report,expectedInputReportChecksumHex?:string):Promise<Result>{if(evidence.status!=="created")return failure("expected-report-mismatch",evidence.error??"Verifier evidence artifacts are unavailable.");if(!Array.isArray(evidence.artifacts)||evidence.artifacts.length!==3)return failure("artifact-count-mismatch","Verifier evidence result must contain exactly three artifacts.");const [plain,json,sum]=evidence.artifacts;if(!plain||!json||!sum||plain.kind!==ORDER[0]||json.kind!==ORDER[1]||sum.kind!==ORDER[2])return failure("artifact-order-mismatch","Verifier evidence artifacts are not in fixed order.");const options:Options={jsonFilename:json.filename,checksumArtifactText:sum.text,checksumArtifactFilename:sum.filename,textEvidenceText:plain.text,textEvidenceFilename:plain.filename,...(expectedVerification?{expectedVerification}:{}),...(expectedReport?{expectedReport}:{}),...(expectedInputReportChecksumHex?{expectedInputReportChecksumHex}:{})};const output=await verifyText(json.text,options);await envelope(evidence,output);finalize(output);return output}
async function envelope(evidence:Evidence,output:Result):Promise<void>{const subtle=globalThis.crypto?.subtle,start=output.issues.length;if(!subtle){output.checks.artifactEnvelope=false;return}if(evidence.artifactCount!==3||evidence.artifacts.length!==3)add(output.issues,"artifact-count-mismatch","$.artifacts","Verifier evidence artifact count must be three.");let total=0;for(let i=0;i<evidence.artifacts.length;i++){const artifact=evidence.artifacts[i],kind=ORDER[i],path=`$.artifacts[${i}]`;if(!artifact||artifact.kind!==kind){add(output.issues,"artifact-order-mismatch",path,"Verifier evidence artifact kind is out of order.");continue}const bytes=new TextEncoder().encode(artifact.text).byteLength,hash=await digest(artifact.text,subtle),mime=kind===ORDER[1]?JSON_MIME:TEXT;total+=bytes;if(!safe(artifact.filename)||artifact.mimeType!==mime||artifact.bytes!==bytes)add(output.issues,"artifact-metadata-mismatch",path,"Artifact filename, MIME type, or byte size is invalid.");if(artifact.checksumHex!==hash)add(output.issues,"sha256-mismatch",`${path}.checksumHex`,`Artifact SHA-256 does not match exact text.`)}filenames(evidence.artifacts,output);if(evidence.totalBytes!==total)add(output.issues,"artifact-metadata-mismatch","$.totalBytes","Verifier evidence totalBytes does not match exact artifact bytes.");if(output.document&&evidence.document&&!equal(output.document,evidence.document))add(output.issues,"expected-report-mismatch","$.document","Verifier evidence document does not match its JSON artifact.");output.checks.artifactEnvelope=output.issues.length===start}
function filenames(a:Artifact[],output:Result):void{const [plain,json,sum]=a;if(!plain||!json||!sum||!json.filename.endsWith(".json"))return;const base=json.filename.slice(0,-5);if(plain.filename!==`${base}.txt`||sum.filename!==`${json.filename}.sha256`)add(output.issues,"artifact-metadata-mismatch","$.artifacts","Verifier evidence artifact filenames are inconsistent.")}
function failure(code:Result["issues"][number]["code"],message:string):Result{const c=checks(true,true);c.artifactEnvelope=false;const a=anchors(false,false,false,true,true),issues:Result["issues"]=[];add(issues,code,"$",message);return result(null,null,0,null,issues,c,a)}
