import type {RuntimeNavMissionDiagnosticsManifestHudValidationArtifactBundleImportedArchiveProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationIssue as Issue} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationContract.js";
import {add,isRecord,safe,sha,type Limits} from "./NavMissionDiagnosticsManifestHudValidationArtifactBundleExtractionArchiveImportedArtifactProvenanceVerificationReportVerificationEvidenceArtifactVerificationResultArtifactVerificationSupport.js";
export type RecordValue=Record<string,unknown>;
export function record(v:unknown,path:string,issues:Issue[]):RecordValue|null{if(isRecord(v))return v;add(issues,"field-type-invalid",path,"Value must be a plain object.");return null}
export function exact(v:RecordValue,fields:readonly string[],path:string,issues:Issue[]):void{const s=new Set(fields);for(const k of Object.keys(v))if(!s.has(k))add(issues,"unknown-field",`${path}.${k}`,`Unknown field ${k}.`);for(const f of fields)if(!Object.hasOwn(v,f))add(issues,"field-type-invalid",`${path}.${f}`,`Missing field ${f}.`)}
export function boolean(v:unknown,path:string,issues:Issue[]):boolean|null{if(typeof v==="boolean")return v;add(issues,"field-type-invalid",path,"Value must be boolean.");return null}
export function integer(v:unknown,path:string,issues:Issue[]):number|null{if(typeof v==="number"&&Number.isSafeInteger(v)&&v>=0)return v;add(issues,"field-type-invalid",path,"Value must be a non-negative safe integer.");return null}
export function string(v:unknown,path:string,max:number,issues:Issue[]):string|null{if(typeof v==="string"&&v.length>0&&v.length<=max)return v;add(issues,"field-value-invalid",path,`Value must be a string of 1-${max} characters.`);return null}
export function nullableString(v:unknown,path:string,max:number,issues:Issue[]):string|null{return v===null?null:string(v,path,max,issues)}
export function filename(v:unknown,path:string,issues:Issue[]):string|null{const x=string(v,path,255,issues);if(x&&!safe(x)){add(issues,"field-value-invalid",path,"Filename must be a safe basename.");return null}return x}
export function checksum(v:unknown,path:string,issues:Issue[]):string|null{if(sha(v))return v;add(issues,"field-value-invalid",path,"Value must be lowercase SHA-256 hex.");return null}
export function trust(v:unknown,path:string,issues:Issue[]):"anchored"|"self-consistent"|"untrusted"|null{if(v==="anchored"||v==="self-consistent"||v==="untrusted")return v;add(issues,"field-value-invalid",path,"Invalid trust value.");return null}
export function boolRecord(v:RecordValue|null,fields:readonly string[],path:string,issues:Issue[],nullable=false):boolean{if(!v)return false;const n=issues.length;exact(v,fields,path,issues);for(const f of fields)if(!(nullable&&v[f]===null))boolean(v[f],`${path}.${f}`,issues);return issues.length===n}
export function bounds(v:unknown,path:string,depth:number,limits:Limits,issues:Issue[]):void{if(depth>limits.maxDepth){add(issues,"field-value-invalid",path,"Maximum nesting depth exceeded.");return}if(typeof v==="string"){if(v.length>limits.maxStringCharacters)add(issues,"string-size-invalid",path,"String limit exceeded.");return}if(Array.isArray(v)){if(v.length>limits.maxArrayEntries){add(issues,"array-size-invalid",path,"Array limit exceeded.");return}v.forEach((x,i)=>bounds(x,`${path}[${i}]`,depth+1,limits,issues));return}if(isRecord(v)){const k=Object.keys(v);if(k.length>limits.maxObjectFields){add(issues,"field-value-invalid",path,"Object field limit exceeded.");return}k.forEach(x=>bounds(v[x],`${path}.${x}`,depth+1,limits,issues))}}
