import {RUNTIME_NAV_MISSION_DIAGNOSTICS_RESULT_VERIFICATION_VERIFIER_EVIDENCE_VERIFICATION_RESULT_ORDER as SOURCE_ORDER} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultArtifact as SourceArtifact,RuntimeNavMissionDiagnosticsResultVerificationVerifierEvidenceVerificationResultEvidence as Source} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationResult as Verification} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerificationContract.js";
import {normalizeIssue} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceIssue.js";
import {JSON_MIME,checksum as normalizedChecksum,integer,safe as isSafe,string,target as normalizeTarget} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceSupport.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceDocument as Document} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceContract.js";
import type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceAnchoredVerificationOptions as Options,RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationResult as Result} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationContract.js";
import {verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceText as verifyText} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationVerification.js";
import {add,digest,equal,finalize} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationSupport.js";
export type {RuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceAnchoredVerificationOptions} from "./NavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceVerificationContract.js";
const MAX=512;
export async function verifyRuntimeNavMissionDiagnosticsVerifierEvidenceVerificationResultVerifierEvidenceTextAnchored(text:string,options:Options={}):Promise<Result>{const core={...(options.maxTextBytes===undefined?{}:{maxTextBytes:options.maxTextBytes}),...(options.maxStringCharacters===undefined?{}:{maxStringCharacters:options.maxStringCharacters}),...(options.maxArrayEntries===undefined?{}:{maxArrayEntries:options.maxArrayEntries}),...(options.maxObjectFields===undefined?{}:{maxObjectFields:options.maxObjectFields}),...(options.maxDepth===undefined?{}:{maxDepth:options.maxDepth}),...(options.jsonFilename===undefined?{}:{jsonFilename:options.jsonFilename}),...(options.checksumArtifactText===undefined?{}:{checksumArtifactText:options.checksumArtifactText}),...(options.checksumArtifactFilename===undefined?{}:{checksumArtifactFilename:options.checksumArtifactFilename}),...(options.textEvidenceText===undefined?{}:{textEvidenceText:options.textEvidenceText}),...(options.textEvidenceFilename===undefined?{}:{textEvidenceFilename:options.textEvidenceFilename}),...(options.expectedInputResultChecksumHex===undefined?{}:{expectedInputResultChecksumHex:options.expectedInputResultChecksumHex})};const result=await verifyText(text,core);if(result.document)await trusted(result.document,options,result);else{if(options.expectedVerification)result.anchors.expectedVerification=false;if(options.expectedSource)result.anchors.expectedSource=false}finalize(result);return result}
async function trusted(document:Document,o:Options,result:Result):Promise<void>{await verifyExpectedVerification(document,o.expectedVerification,o.expectedSource,result);await verifyExpectedSource(document,o.expectedSource,result)}
async function verifyExpectedVerification(document:Document,expected:Verification|undefined,source:Source|undefined,result:Result):Promise<void>{if(!expected)return;const issues=Array.isArray(expected.issues)?expected.issues:[],expectedIssues=issues.slice(0,MAX).map(normalizeIssue),subtle=globalThis.crypto?.subtle;let canonicalMatches=false;if(typeof expected.canonicalText==="string"&&subtle)canonicalMatches=await digest(expected.canonicalText,subtle)===document.input.exactChecksum.hex;const expectedEvidence={documentAvailable:expected.document!==null,canonicalTextAvailable:typeof expected.canonicalText==="string",canonicalTextMatchesInput:canonicalMatches,verificationChecksumAvailable:typeof expected.checksumHex==="string",verificationChecksumMatchesInput:typeof expected.checksumHex==="string"&&expected.checksumHex===document.input.exactChecksum.hex,issuesTruncated:issues.length>MAX},recorded=source?.document??expected.document,target=normalizeTarget(expected.document?.target??source?.document?.target??null),expectedRecorded={schema:typeof recorded?.schema==="string"?recorded.schema:null,schemaVersion:Number.isSafeInteger(recorded?.schemaVersion)?recorded!.schemaVersion:null,verifierEvidenceVerificationValid:typeof recorded?.result?.valid==="boolean"?recorded.result.valid:null,verifierEvidenceVerificationTrust:recorded?.result?.trust??null};const valid=document.result.valid===expected.valid&&document.result.trust===expected.trust&&document.result.issueCount===issues.length&&equal(document.checks,expected.checks)&&equal(document.anchors,expected.anchors)&&equal(document.evidence,expectedEvidence)&&equal(document.issues,expectedIssues)&&equal(document.recordedResult,expectedRecorded)&&equal(document.target,target)&&(expected.checksumHex===null||expected.checksumHex===document.input.exactChecksum.hex);if(!valid)add(result.issues,"expected-verification-mismatch","$","Verifier evidence does not match the expected verification-result artifact verifier result.");result.anchors.expectedVerification=valid}
async function verifyExpectedSource(document:Document,expected:Source|undefined,result:Result):Promise<void>{if(!expected)return;const artifact=one(expected.artifacts),subtle=globalThis.crypto?.subtle;if(!artifact||!subtle){add(result.issues,"expected-source-mismatch","$.input","Expected verification-result JSON artifact is unavailable.");result.anchors.expectedSource=false;return}const text=typeof artifact.text==="string"?artifact.text:"",hash=await digest(text,subtle),name=typeof artifact.filename==="string"?artifact.filename:"",mime=typeof artifact.mimeType==="string"?artifact.mimeType:"",declaredBytes=typeof artifact.bytes==="number"?artifact.bytes:-1,declaredHash=typeof artifact.checksumHex==="string"?artifact.checksumHex:"",exactBytes=new TextEncoder().encode(text).byteLength,safeName=isSafe(name),recorded=expected.document,expectedRecorded={schema:typeof recorded?.schema==="string"?recorded.schema:null,schemaVersion:Number.isSafeInteger(recorded?.schemaVersion)?recorded!.schemaVersion:null,verifierEvidenceVerificationValid:typeof recorded?.result?.valid==="boolean"?recorded.result.valid:null,verifierEvidenceVerificationTrust:recorded?.result?.trust??null};const valid=document.input.verificationResultJsonFilename===(safeName?name:"mission-diagnostics-policy-manifest.verifier-evidence.verification-result.json")&&document.input.verificationResultJsonMimeType===string(mime,255,"application/octet-stream")&&document.input.declaredBytes===integer(declaredBytes)&&document.input.exactBytes===exactBytes&&document.input.declaredChecksumHex===normalizedChecksum(declaredHash)&&document.input.exactChecksum.hex===hash&&document.input.envelope.filenameSafe===safeName&&document.input.envelope.mimeTypeMatches===(mime===JSON_MIME)&&document.input.envelope.byteSizeMatches===(declaredBytes===exactBytes)&&document.input.envelope.checksumMatches===(declaredHash===hash)&&equal(document.recordedResult,expectedRecorded)&&equal(document.target,normalizeTarget(expected.document?.target??null));if(!valid)add(result.issues,"expected-source-mismatch","$.input","Verifier evidence input does not match the expected verification-result artifact set.");result.anchors.expectedSource=valid}
function one(artifacts:SourceArtifact[]|undefined):SourceArtifact|null{if(!Array.isArray(artifacts))return null;const found=artifacts.filter(x=>x?.kind===SOURCE_ORDER[1]);return found.length===1?found[0]??null:null}
